export enum EventEnum {
  ON = 'atlas-shared:events:on',
  ONCE = 'atlas-shared:events:once',
  ON_SERVER = 'atlas-shared:events:onServer',
  ONCE_SERVER = 'atlas-shared:events:onceServer',
  ON_CLIENT = 'atlas-shared:events:onClient',
  ONCE_CLIENT = 'atlas-shared:events:onceClient',
  ON_GUI = 'atlas-shared:events:onGui',
  GAME_ENTITY_CREATE = 'atlas-shared:events:gameEntityCreate',
  GAME_ENTITY_DESTROY = 'atlas-shared:events:gameEntityDestroy',
  STREAM_SYNCED_META_CHANGE = 'atlas-shared:events:streamSyncedMetaChange',
  SYNCED_META_CHANGE = 'atlas-shared:events:syncedMetaChange',
  ENTITY_ENTER_COLSHAPE = 'atlas-shared:events:entityEnterColShape',
  ENTITY_LEAVE_COLSHAPE = 'atlas-shared:events:entityLeaveColShape',
  CONSOLE_COMMAND = 'atlas-shared:events:consoleCommand',
  KEY_UP = 'atlas-shared:events:keyUp',
  KEY_DOWN = 'atlas-shared:events:keyDown',
}
