name: Build & Publish
on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*.*'

jobs:
  build-publish:
    name: Build & Publish
    runs-on: ubuntu-18.04
    env:
      NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Install Node.js v16 with NPM Registry
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Restore dependency cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn --frozen-lockfile
          yarn global add lerna

      # Publish atlas-framework packages
      - name: Build atlas-framework packages
        run: yarn build

      - name: Publish atlas-framework packages
        run: lerna publish from-package --no-git-tag-version --no-push --no-verify-access --yes
